### PR TITLE
Workflow refactoring

### LINKED ISSUE #213: Parallelize the CI checks

### PR DESCRIPTION
**Pull request by illright**
Closes #213. Check the commit history for the changelog

### CODE REVIEW

**Comment by illright** [comment]
Some actions didn't set off because I changed the event from `pull_request` to `pull_request_target`. Hopefully that's the only reason :)

**Comment by illright** [comment]
Yeah, but checkout is easy, install is handled with cache, no build needed. I think it's not very costly, and it's definitely useful to have unit and E2E tests running in parallel

**Review by aabounegm — APPROVED** [review]

**Comment by illright** [comment]
@aabounegm can you merge this with admin privileges?

**Comment by aabounegm** [comment]
No, but I could remove the status check requirement

**Pull request merged**
