### PR TITLE
Feature: configure unit testing

### LINKED ISSUE #9: Configure unit testing in `app`
Blocked by #2 

Use the Svelte Testing Library with Jest.

**Acceptance criteria**:
- `pnpm test:unit` in the `app` project runs the test suite

### PR DESCRIPTION
**Pull request by khaledismaeel**
Resolves #9.

### CODE REVIEW

**Comment by aabounegm** [comment]
Pair-programmed avec moi, but we still want feedback over where to place the tests (next to the component, or in `tests` or `__tests__` directory?), and also on consistency in the config files format (like, we `.babelrc`, but `jest.config.mjs`)

**Comment by illright** [comment]
I think that tests should be placed in slices of functionality, i.e. one level below the components

Regarding config files, do we really need Babel? I think it wasn't necessary when I was configuring the testing of Apparitions

**Comment by khaledismaeel** [comment]
I don't have concrete information on whether Babel is really needed here or not, but if I understood correctly, we need it for compatibility of TS and ES6 (we weren't sure what we're gonna be dealing with so we just decided to stay safe).

Do you suggest to remove it?

**Comment by illright** [comment]
It's fine for now, maybe I'll look into removing it in the future

**Review by illright — APPROVED** [review]

**Pull request merged**
